name: Release-o-bot
on:
  push:
    branches:
    - main
jobs:
  package_as_zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Package root repository contents as a ZIP file.
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'cobalt2.xpi'
        exclusions: '*.git* *.github*'
    - name: Tag recent commit on main
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
    - name: Upload artifact and release on GitHub
      uses: ncipollo/release-action@v1.12.0
      with:
        artifactErrorsFailBuild: true
        artifacts: "cobalt2.xpi"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
      
