name: Release-o-bot
on:
  push:
    branches:
      - main
jobs:
  package_as_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag recent commit on main
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Insert extension version into manifest.json
        uses: jossef/action-set-json-field@v2.1
        with:
          file: manifest.json
          field: version
          value: ${{ steps.tag_version.outputs.new_tag }}
      - name: Read minimum TB version
        id: strict_min_version
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "manifest.json"
          prop_path: "browser_specific_settings.gecko.strict_min_version"
      - name: Read maximum TB version
        id: strict_max_version
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "manifest.json"
          prop_path: "browser_specific_settings.gecko.strict_max_version"
      - name: Package root repository contents as a ZIP file.
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "cobalt2.xpi"
          exclusions: "*.git* *.github* *.vscode*"
      - name: Upload artifact and release on GitHub
        uses: ncipollo/release-action@v1.12.0
        with:
          artifactErrorsFailBuild: true
          artifacts: "cobalt2.xpi"
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            This release supports the following Thunderbird versions:
            - at least (inclusive) version ${{ steps.strict_min_version.outputs.value }}
            - at most (inclusive) version ${{ steps.strict_max_version.outputs.value }}

            > You can download the extension by right-clicking the ".xpi" file below and selecting "Save Link As...".

            ## Changelog
            ${{ steps.tag_version.outputs.changelog }}
